### ISSUE TITLE
ruby_stripe.h missing

### ISSUE THREAD

**Issue by matjam** [astrofra/system-zoetrope-amiga-demo#13]
`m68k-amigaos-gcc -c -noixemul -s -Os -Wall -fomit-frame-pointer -m68000 -msmall-code -I/home/chrome/Development/amiga/projet-secret/../m68k-amigaos/os-include/ -I/home/chrome/Development/amiga/projet-secret/include/ /home/chrome/Development/amiga/projet-secret/src/font_bitmap.c -o /home/chrome/Development/amiga/projet-secret/src/font_bitmap.o
m68k-amigaos-gcc -MM -noixemul -s -Os -Wall -fomit-frame-pointer -m68000 -msmall-code /home/chrome/Development/amiga/projet-secret/src/font_bitmap.c > /home/chrome/Development/amiga/projet-secret/src/font_bitmap.d
m68k-amigaos-gcc -c -noixemul -s -Os -Wall -fomit-frame-pointer -m68000 -msmall-code -I/home/chrome/Development/amiga/projet-secret/../m68k-amigaos/os-include/ -I/home/chrome/Development/amiga/projet-secret/include/ /home/chrome/Development/amiga/projet-secret/src/3d_objects.c -o /home/chrome/Development/amiga/projet-secret/src/3d_objects.o
m68k-amigaos-gcc -MM -noixemul -s -Os -Wall -fomit-frame-pointer -m68000 -msmall-code /home/chrome/Development/amiga/projet-secret/src/3d_objects.c > /home/chrome/Development/amiga/projet-secret/src/3d_objects.d
m68k-amigaos-gcc -c -noixemul -s -Os -Wall -fomit-frame-pointer -m68000 -msmall-code -I/home/chrome/Development/amiga/projet-secret/../m68k-amigaos/os-include/ -I/home/chrome/Development/amiga/projet-secret/include/ /home/chrome/Development/amiga/projet-secret/src/cosine_table.c -o /home/chrome/Development/amiga/projet-secret/src/cosine_table.o
m68k-amigaos-gcc -MM -noixemul -s -Os -Wall -fomit-frame-pointer -m68000 -msmall-code /home/chrome/Development/amiga/projet-secret/src/cosine_table.c > /home/chrome/Development/amiga/projet-secret/src/cosine_table.d
m68k-amigaos-gcc -c -noixemul -s -Os -Wall -fomit-frame-pointer -m68000 -msmall-code -I/home/chrome/Development/amiga/projet-secret/../m68k-amigaos/os-include/ -I/home/chrome/Development/amiga/projet-secret/include/ /home/chrome/Development/amiga/projet-secret/src/font_desc.c -o /home/chrome/Development/amiga/projet-secret/src/font_desc.o
m68k-amigaos-gcc -MM -noixemul -s -Os -Wall -fomit-frame-pointer -m68000 -msmall-code /home/chrome/Development/amiga/projet-secret/src/font_desc.c > /home/chrome/Development/amiga/projet-secret/src/font_desc.d
m68k-amigaos-gcc -c -noixemul -s -Os -Wall -fomit-frame-pointer -m68000 -msmall-code -I/home/chrome/Development/amiga/projet-secret/../m68k-amigaos/os-include/ -I/home/chrome/Development/amiga/projet-secret/include/ /home/chrome/Development/amiga/projet-secret/src/bob_bitmaps.c -o /home/chrome/Development/amiga/projet-secret/src/bob_bitmaps.o
m68k-amigaos-gcc -MM -noixemul -s -Os -Wall -fomit-frame-pointer -m68000 -msmall-code /home/chrome/Development/amiga/projet-secret/src/bob_bitmaps.c > /home/chrome/Development/amiga/projet-secret/src/bob_bitmaps.d
m68k-amigaos-gcc -c -noixemul -s -Os -Wall -fomit-frame-pointer -m68000 -msmall-code -I/home/chrome/Development/amiga/projet-secret/../m68k-amigaos/os-include/ -I/home/chrome/Development/amiga/projet-secret/include/ /home/chrome/Development/amiga/projet-secret/src/sprites_routines.c -o /home/chrome/Development/amiga/projet-secret/src/sprites_routines.o
/home/chrome/Development/amiga/projet-secret/src/sprites_routines.c:6:25: fatal error: ruby_stripe.h: No such file or directory
 #include "ruby_stripe.h"
                         ^
compilation terminated.
Makefile:22: recipe for target '/home/chrome/Development/amiga/projet-secret/src/sprites_routines.o' failed
make: *** [/home/chrome/Development/amiga/projet-secret/src/sprites_routines.o] Error 1
`

**Comment by astrofra** [comment]
Fixed.
Thanks for mentioning this one.
Please keep in mind this project was built using SAS/C.
It might not compile directly on a more recent compiler.
